---
- hosts: web
  become: yes
  vars_files:
    - vars/default.yml
  gather_facts: true
  tasks:
    - name: "instalação de pacotes webserver"
      become: yes
      apt:
        pkg:
          - php7.4
          - php-pear
          - php7.4-curl
          - php7.4-gd
          - php7.4-intl
          - php7.4-xmlrpc
          - php7.4-mysql
          - apache2
          - python3-mysqldb
          - wget
          - zip
          - curl
          - vim
        state: present
      when: ansible_os_family == 'Debian'
    - name: "Diretorio do webserver"
      become: yes
      file:
        path: /srv/www
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0775'
    - name: "download e extração do arquivo da aplicação"
      unarchive:
        src: https://github.com/rogerramossilva/devops/raw/master/express.zip
        dest: /srv/www
        remote_src: yes
    - name: "Substitui IP de conexão com o banco"
      replace:
        path: /srv/www/express/backup.php
        regexp: '192\.168\.1\.20'
        replace: '172.17.177.102'
    - name: "criando virtual host para pagina express.asf.com"
      template: 
        src: "files/express.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
    - name: "controle de diretório virtual host"
      template:
        src: "files/direxpress.conf"
        dest: "/etc/apache2/conf-available/direxpress.conf"
    - name: "entrada dns arquivos /etc/hosts"
      template: 
        src: "files/hostsweb.conf"
        dest: "/etc/hosts"
    - name: "habilitar site"
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache
    - name: "habilitar arquivo de configuração express"
      shell: /usr/sbin/a2enconf direxpress.conf
      notify: Reload Apache
    - name: "habilitar modulo php7"
      apache2_module:
        state: present
        name: php7.4
      notify: Reload Apache
    - name: "habilitar modulo virtual host"
      apache2_module:
        state: present
        name: vhost_alias
      notify: Reload Apache

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
    - name: Reload Apache
      service:
        name: apache2
        state: restarted
    - name: Reload Apache
      service:
        name: apache2
        state: started


